CREATE DATABASE projetoweb;



-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 10:25:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoweb` DEFAULT CHARACTER SET utf8 ;
USE `projetoweb` ;

-- -----------------------------------------------------
-- Table `projetoweb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoweb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT NOT NULL,
  `idusuario` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoweb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoweb`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `cnpj` INT NOT NULL,
  `razao_social` VARCHAR(200) NOT NULL,
  `nome_fantasia` VARCHAR(200) NOT NULL,
  `idusuario` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoweb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoweb`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `idcliente` INT NOT NULL,
  `idempresa` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `projetoweb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_empresa1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `projetoweb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_endereco_cliente_idx` ON `projetoweb`.`endereco` (`idcliente` ASC) VISIBLE;

CREATE INDEX `fk_endereco_empresa1_idx` ON `projetoweb`.`endereco` (`idempresa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoweb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoweb`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `pessoal` INT NULL,
  `residencial` INT NULL,
  `idcliente` INT NOT NULL,
  `idempresa` INT NOT NULL,
  PRIMARY KEY (`idtelefone`),
  CONSTRAINT `fk_telefone_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `projetoweb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_empresa1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `projetoweb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_cliente1_idx` ON `projetoweb`.`telefone` (`idcliente` ASC) VISIBLE;

CREATE INDEX `fk_telefone_empresa1_idx` ON `projetoweb`.`telefone` (`idempresa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoweb`.`ordemservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoweb`.`ordemservico` (
  `idordemservico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `custo` INT NOT NULL,
  `prazo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `idcliente` INT NOT NULL,
  `idservico` VARCHAR(150) NOT NULL,
  `idorcamento` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idordemservico`),
  CONSTRAINT `fk_ordemservico_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `projetoweb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ordemservico_cliente1_idx` ON `projetoweb`.`ordemservico` (`idcliente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
